### ISSUE TITLE
Smart contract panicked: panicked at 'called `Result::unwrap()` on an `Err` value: RlpIsTooShort', eth-prover/src/lib.rs:121:71

### ISSUE THREAD

**Issue by HanHanPecan** [aurora-is-near/rainbow-bridge#638] opened 2021-10-25 12:19 UTC
When I send token from eth to near, i have finished lock token in eth blockchain. Then near blockchain add eth block header, when near deposit token to address, the bug was happened.

**Comment by mfornet** [comment] 2021-11-17 14:36
Can you share the hash of the tx where this happened. Either the hash on Ethereum or NEAR (preferably the latter)

**Comment by sept-en** [comment] 2021-11-17 16:13
Probably a duplicate of #616. If the issue is still present - please reopen and add more comments to it.

**Closed by sept-en** 2021-11-17 16:13 UTC
